finding_work/main/routes.py
from flask import render_template, Blueprint, request, url_for, redirect
from flask import current_app
from flask_login import login_required, current_user
from finding_work.main.api_hh import receive_all_id
from finding_work.models import Post, db
from finding_work.main.forms import NoteForm, StatusForm

main = Blueprint('main', __name__)


@main.route("/")
def home():
    statistics = {}
    if request.args.get('sort') == 'filter_exp':
        all = Post.query.filter(
            Post.status != 'CLOSED').order_by(Post.experience)
    elif request.args.get('sort') == 'filter_status':
        all = Post.query.filter(
            Post.status != 'CLOSED').order_by(Post.status)
    else:
        all = Post.query.filter(Post.status != 'CLOSED')
    statistics['all'] = Post.query.filter(Post.status != 'CLOSED').count()
    statistics['answer'] = Post.query.filter(Post.status == 'ANSWER').count()
    statistics['reject'] = Post.query.filter(Post.status == 'REJECT').count()
    return render_template('index.html', content=all, count=statistics)


@main.route("/detail/<int:post_id>", methods=['GET', 'POST'])
def detail(post_id):
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if current_user.user_status == 'GUEST':
        cur_user = 1
    else:
        cur_user = current_user.id
    form = NoteForm()
    form2 = StatusForm()
    all = Post.query.filter(Post.status != 'CLOSED',
                            Post.user_id == cur_user)
    post = Post.query.filter(
        Post.id == post_id, Post.user_id == cur_user).one()
    statistics = {}
    if request.method == 'GET':
        if post.note:
            form.note.data = post.note
        form2.status.data = post.status.name
    elif request.method == 'POST':
        if form.note.data and form.note.data != post.note:
            if form.validate_on_submit():
                post.note = form.note.data
                form2.status.data = post.status.name
                db.session.commit()
        if form2.validate_on_submit():
            post.status = form2.status.data
            db.session.commit()
            current_app.logger.warning(
                f'У вакансии с ID {post.id} - {post.author} был изменён статус.')
    statistics['all'] = Post.query.filter(
        Post.status != 'CLOSED', Post.user_id == cur_user).count()
    statistics['answer'] = Post.query.filter(
        Post.status == 'ANSWER', Post.user_id == cur_user).count()
    statistics['reject'] = Post.query.filter(
        Post.status == 'REJECT', Post.user_id == cur_user).count()
    return render_template('detail.html', content=all, count=statistics, post=post, form=form, form2=form2)


@main.route("/receive_data", methods=['GET', 'POST'])
def receive_data():
    if receive_all_id():
        current_app.logger.warning(
            f'База данных успешно обновлена.')
    else:
        current_app.logger.error(
            f'В процессе обновления произошли ошибки.')
    return redirect(url_for('main.home'))

finding_work/user/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from finding_work.models import User, db, bcrypt
from finding_work.user.forms import RegistrationForm, LoginForm
from finding_work.config import Config

user = Blueprint('user', __name__)


@user.route("/user/registration", methods=['POST', 'GET'])
def registrations():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit() and form.code.data == Config.KEY_REGISTER:
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    password=hashed_password, user_status=form.user_status.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.authentication'))
    return render_template('registration.html', title='Register', form=form)


@user.route("/user/authentication", methods=['GET', 'POST'])
def authentication():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user)
            return redirect(url_for('main.home'))
    return render_template('authentication.html', title='Аутентификация', form=form)


@user.route("/user/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

finding_work/templates/authentication.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Hope UI | Responsive Bootstrap 5 Admin Dashboard Template</title>

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.ico') }}"
    />

    <!-- Library / Plugin Css Build -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/libs.min.css') }}"
    />

    <!-- Custom Css -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/hope-ui.css') }}"
    />
  </head>
  <body>
    <div class="container" style="margin: 50 auto">
      <div class="" style="margin: 70px auto">
        <div class="card">
          <div class="card-header d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Форма авторизации</h4>
            </div>
          </div>
          <div class="card-body">
            <p>Форма авторизации.</p>
            <form method="post" action="">
                {{ form.csrf_token }}
              <div class="form-group">
                <label class="form-label" for="email">Логин:</label>
                {{ form.username(class="form-control") }}
              </div>
              <div class="form-group">
                <label class="form-label" for="pwd">Пароль:</label>
                {{ form.password(class="form-control") }}
              </div>
              {{ form.submit(class="btn btn-primary") }}
              <a href="{{ url_for("main.home")}}" class="btn btn-danger">На главную</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

finding_work/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Hope UI | Responsive Bootstrap 5 Admin Dashboard Template</title>

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.ico') }}"
    />

    <!-- Library / Plugin Css Build -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/libs.min.css') }}"
    />

    <!-- Custom Css -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/hope-ui.css') }}"
    />
  </head>
  <body class="dual-compact">
    <span class="screen-darken"></span>
    <!-- loader Start -->
    <div id="loading">
      <div class="loader simple-loader">
        <div class="loader-body"></div>
      </div>
    </div>
    <!-- loader END -->
    <main class="main-content">
      <!--Nav Start-->
      <nav
        class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark iq-navbar"
        aria-label="Main navigation"
      >
        <div class="container-fluid">
          <a
            href="{{ url_for ('main.home') }}"
            class="navbar-brand d-flex align-items-center"
          >
            <!--Logo start-->
            <svg
              width="30"
              class=""
              viewBox="0 0 30 30"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect
                x="-0.757324"
                y="19.2427"
                width="28"
                height="4"
                rx="2"
                transform="rotate(-45 -0.757324 19.2427)"
                fill="currentColor"
              />
              <rect
                x="7.72803"
                y="27.728"
                width="28"
                height="4"
                rx="2"
                transform="rotate(-45 7.72803 27.728)"
                fill="currentColor"
              />
              <rect
                x="10.5366"
                y="16.3945"
                width="16"
                height="4"
                rx="2"
                transform="rotate(45 10.5366 16.3945)"
                fill="currentColor"
              />
              <rect
                x="10.5562"
                y="-0.556152"
                width="28"
                height="4"
                rx="2"
                transform="rotate(45 10.5562 -0.556152)"
                fill="currentColor"
              />
            </svg>
            <!--logo End-->
            <h4 class="logo-title text-light ms-3 mb-0">Поиск работы</h4>
          </a>
          <button
            class="navbar-toggler p-0 border-0"
            type="button"
            id="navbarSideCollapse"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon">
              <span class="navbar-toggler-bar bar1 mt-2"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>

          <div
            class="navbar-collapse offcanvas-collapse"
            id="navbarsExampleDefault"
          >
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.logout')}}"
                  >LOG_IN: {{current_user.username}} - {{current_user.user_status}}, Выйти</a
                >
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.authentication')}}"
                  >Войти</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.registrations')}}"
                  >Регистрация</a
                >
              </li>
              {% endif %}
            </ul>
            <!--
            <form class="d-flex">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button class="btn btn-primary" type="submit">Search</button>
            </form>
          --></div>
        </div>
      </nav>

      <!--Nav End-->
      <div class="conatiner-fluid content-inner pb-0">
        <div class="row">
          <div class="col-md-12 col-lg-12">
            <div class="row row-cols-1">
              <div class="d-slider1 overflow-hidden">
                <ul class="swiper-wrapper list-inline m-0 p-0 mb-2">
                  <li class="swiper-slide card card-slide">
                    <div class="card-body">
                      <div class="progress-widget">
                        <div class="progress-detail">
                          <p class="mb-2">Всего вакансий</p>
                          <h4 class="counter">{{count.all}}</h4>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="swiper-slide card card-slide">
                    <div class="card-body">
                      <div class="progress-widget">
                        <div class="progress-detail">
                          <p class="mb-2">Всего откликов</p>
                          <h4 class="counter">{{count.answer}}</h4>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="swiper-slide card card-slide">
                    <div class="card-body">
                      <div class="progress-widget">
                        <div class="progress-detail">
                          <p class="mb-2">Всего отказов</p>
                          <h4 class="counter">{{count.reject}}</h4>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li
                    id="screen"
                    class="swiper-slide card card-slide"
                    style="display: none"
                  >
                    <div class="card-body">
                      <div class="progress-widget">
                        <div class="progress-detail">
                          <div class="alert alert-warning" role="alert">
                            <h4 class="alert-heading">Внимание!</h4>
                            <p>Происходит проверка актуальности объявлений.</p>
                            <hr />
                            <p class="mb-0">Дождитесь окончания процесса.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
                <div class="swiper-button swiper-button-next"></div>
                <div class="swiper-button swiper-button-prev"></div>
              </div>
            </div>
          </div>
          {% block content %} {% endblock %}
        </div>
      </div>
      <!-- Footer Section Start -->
      <footer class="footer">
        <div class="footer-body">
          <ul class="left-panel list-inline mb-0 p-0">
            <li class="list-inline-item">
              <a href="../dashboard/extra/privacy-policy.html"
                >Privacy Policy</a
              >
            </li>
            <li class="list-inline-item">
              <a href="../dashboard/extra/terms-of-service.html"
                >Terms of Use</a
              >
            </li>
          </ul>
          <div class="right-panel">
            ©
            <script>
              document.write(new Date().getFullYear());
            </script>
            Hope UI, Made with
            <span class="text-gray">
              <svg
                width="15"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill-rule="evenodd"
                  clip-rule="evenodd"
                  d="M15.85 2.50065C16.481 2.50065 17.111 2.58965 17.71 2.79065C21.401 3.99065 22.731 8.04065 21.62 11.5806C20.99 13.3896 19.96 15.0406 18.611 16.3896C16.68 18.2596 14.561 19.9196 12.28 21.3496L12.03 21.5006L11.77 21.3396C9.48102 19.9196 7.35002 18.2596 5.40102 16.3796C4.06102 15.0306 3.03002 13.3896 2.39002 11.5806C1.26002 8.04065 2.59002 3.99065 6.32102 2.76965C6.61102 2.66965 6.91002 2.59965 7.21002 2.56065H7.33002C7.61102 2.51965 7.89002 2.50065 8.17002 2.50065H8.28002C8.91002 2.51965 9.52002 2.62965 10.111 2.83065H10.17C10.21 2.84965 10.24 2.87065 10.26 2.88965C10.481 2.96065 10.69 3.04065 10.89 3.15065L11.27 3.32065C11.3618 3.36962 11.4649 3.44445 11.554 3.50912C11.6104 3.55009 11.6612 3.58699 11.7 3.61065C11.7163 3.62028 11.7329 3.62996 11.7496 3.63972C11.8354 3.68977 11.9247 3.74191 12 3.79965C13.111 2.95065 14.46 2.49065 15.85 2.50065ZM18.51 9.70065C18.92 9.68965 19.27 9.36065 19.3 8.93965V8.82065C19.33 7.41965 18.481 6.15065 17.19 5.66065C16.78 5.51965 16.33 5.74065 16.18 6.16065C16.04 6.58065 16.26 7.04065 16.68 7.18965C17.321 7.42965 17.75 8.06065 17.75 8.75965V8.79065C17.731 9.01965 17.8 9.24065 17.94 9.41065C18.08 9.58065 18.29 9.67965 18.51 9.70065Z"
                  fill="currentColor"
                ></path>
              </svg>
            </span>
            by <a href="https://iqonic.design/">IQONIC Design</a>.
          </div>
        </div>
      </footer>
      <!-- Footer Section End -->
    </main>
    <!-- Wrapper End-->
    <!-- Backend Bundle JavaScript -->
    <script src="{{ url_for('static', filename='js/libs.min.js') }}"></script>

    <!-- widgetchart JavaScript -->
    <script src="{{ url_for('static', filename='js/charts/widgetcharts.js') }}"></script>

    <!-- mapchart JavaScript -->
    <script src="{{ url_for('static', filename='js/charts/vectore-chart.js') }}"></script>
    <script src="{{ url_for('static', filename='js/charts/dashboard.js') }}"></script>

    <!-- fslightbox JavaScript -->
    <script src="{{ url_for('static', filename='js/fslightbox.js') }}"></script>

    <!-- settings JavaScript -->
    <script src="{{ url_for('static', filename='js/setting.js') }}"></script>

    <!-- Form Wizard Script -->
    <script src="{{ url_for('static', filename='js/form-wizard.js') }}"></script>

    <!-- app JavaScript -->
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  </body>
</html>

finding_work/templates/index.html
{% extends 'base.html' %} {% block content %}

<div class="col-md-12 col-lg-12">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <div class="card overflow-hidden">
        <div class="card-header d-flex justify-content-between flex-wrap">
          <div class="header-title">
            <h4 class="card-title mb-2">Вакансии</h4>
          </div>
          <div class="dropdown">
            Сортировка
            <span
              class="dropdown-toggle"
              id="dropdownMenuButton7"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              role="button"
            >
            </span>
            <div
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="dropdownMenuButton7"
            >
             
              <a class="dropdown-item text-info" href="{{ url_for('main.home', sort="filter_exp") }}"
                >Сортировать по опыту</a
              >
              <a class="dropdown-item text-info" href="{{ url_for('main.home', sort="filter_status") }}"
                >Сортировать по статусу</a
              >
            </div>
          </div>
          {% if current_user.is_authenticated and current_user.user_status == 'CLIENT' %}
          <div class="dropdown">
            Обновление
            <span
              class="dropdown-toggle"
              id="dropdownMenuButton7"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              role="button"
            >
            </span>
            <div
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="dropdownMenuButton7"
            >
             
              <form method="post">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <a id="check_status" class="dropdown-item text-danger" href="{{ url_for('main.receive_data') }}"
                >Обновление вакансий</a
              >
              </form>
              
            </div>
          </div>
          {% endif %}
        </div>
  
        <div class="card-body p-0">
          <div class="table-responsive mt-4">
            <table
              id="basic-table"
              class="table table-striped mb-0"
              role="grid"
            >
              <thead>
                <tr>
                  <th>ID</th>
                  <th>ID на НН</th>
                  <th>КОМПАНИЯ</th>
                  <th>ЗАРПЛАТА</th>
                  <th>НУЖЕН ОПЫТ</th>
                  <th>СТАТУС</th>
                </tr>
              </thead>
              <tbody>
                {% for item in content %}
                <tr>
                  <td>{{item.id}}</td>
                  <td>{{item.id_hh}}</td>
                  <td>
                    <div class="d-flex align-items-center">
                      <h6>
                        <a href="{{url_for('main.detail', post_id=item.id)}}"
                          >{{item.author}}</a
                        >
                      </h6>
                    </div>
                  </td>
                  <td>{{item.salary}}</td>
                  <td {% if item.experience != 'От 1 года до 3 лет' %} class = 'text-success' {% else %} class = 'text-warning' {% endif %}>
                    {{item.experience}}
                  </td>
                  <td {% if item.status.value == 'Откликнулся' %} class = 'text-success' {% elif item.status.value == 'Новое' %} class = 'text-primary' {% else %} class = 'text-warning' {% endif %}>
                    {{item.status.value}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer Section Start 
              <div class="col-md-12 col-xl-6">
                <div class="card">
                  <div
                    class="card-header d-flex justify-content-between flex-wrap"
                  >
                    <div class="header-title">
                      <h4 class="card-title">Earnings</h4>
                    </div>
                    <div class="dropdown">
                      <a
                        href="#"
                        class="text-secondary dropdown-toggle"
                        id="dropdownMenuButton1"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                      >
                        This Week
                      </a>
                      <ul
                        class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="dropdownMenuButton1"
                      >
                        <li><a class="dropdown-item" href="#">This Week</a></li>
                        <li>
                          <a class="dropdown-item" href="#">This Month</a>
                        </li>
                        <li><a class="dropdown-item" href="#">This Year</a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="card-body">
                    <div
                      class="d-flex flex-wrap align-items-center justify-content-between"
                    >
                      <div id="myChart" class="col-md-8 col-lg-8 myChart"></div>
                      <div class="d-grid gap col-md-4 col-lg-4">
                        <div class="d-flex align-items-start">
                          <svg
                            class="mt-2"
                            xmlns="http://www.w3.org/2000/svg"
                            width="14"
                            viewBox="0 0 24 24"
                            fill="#3a57e8"
                          >
                            <g>
                              <circle
                                cx="12"
                                cy="12"
                                r="8"
                                fill="#3a57e8"
                              ></circle>
                            </g>
                          </svg>
                          <div class="ms-3">
                            <span class="text-secondary">Fashion</span>
                            <h6>251K</h6>
                          </div>
                        </div>
                        <div class="d-flex align-items-start">
                          <svg
                            class="mt-2"
                            xmlns="http://www.w3.org/2000/svg"
                            width="14"
                            viewBox="0 0 24 24"
                            fill="#4bc7d2"
                          >
                            <g>
                              <circle
                                cx="12"
                                cy="12"
                                r="8"
                                fill="#4bc7d2"
                              ></circle>
                            </g>
                          </svg>
                          <div class="ms-3">
                            <span class="text-secondary">Accessories</span>
                            <h6>176K</h6>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-12 col-xl-6">
                <div class="card">
                  <div
                    class="card-header d-flex justify-content-between flex-wrap"
                  >
                    <div class="header-title">
                      <h4 class="card-title">Conversions</h4>
                    </div>
                    <div class="dropdown">
                      <a
                        href="#"
                        class="text-secondary dropdown-toggle"
                        id="dropdownMenuButton3"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                      >
                        This Week
                      </a>
                      <ul
                        class="dropdown-menu dropdown-menu-end"
                        aria-labelledby="dropdownMenuButton3"
                      >
                        <li><a class="dropdown-item" href="#">This Week</a></li>
                        <li>
                          <a class="dropdown-item" href="#">This Month</a>
                        </li>
                        <li><a class="dropdown-item" href="#">This Year</a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="card-body">
                    <div id="d-activity" class="d-activity"></div>
                  </div>
                </div>
              </div>
              -->
  </div>
</div>
{% endblock %}

finding_work/templates/registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Hope UI | Responsive Bootstrap 5 Admin Dashboard Template</title>

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.ico') }}"
    />

    <!-- Library / Plugin Css Build -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/libs.min.css') }}"
    />

    <!-- Custom Css -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/hope-ui.css') }}"
    />
  </head>
  <body>
    <div class="container" style="margin: 50 auto">
      <div class="" style="margin: 70px auto">
        <div class="card">
          <div class="card-header d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Форма регистрации</h4>
            </div>
          </div>
          <div class="card-body">
            <p>Форма регистрации. Регистрация предполагает знание кода.</p>
            <form method="post" action="">
                {{ form.csrf_token }}
              <div class="form-group">
                <label class="form-label" for="email">Логин:</label>
                {{ form.username(class="form-control") }}
              </div>
              <div class="form-group">
                <label class="form-label" for="pwd">Пароль:</label>
                {{ form.password(class="form-control") }}
              </div>
              <div class="form-group">
                <label class="form-label" for="pwd">Повторите пароль:</label>
                {{ form.confirm_password(class="form-control") }}
              </div>
              <div class="form-group">
                <label class="form-label" for="pwd">Выберите статус:</label>
                {{ form.user_status(class="form-select") }}
              </div>
              <div class="form-group">
                <label class="form-label" for="pwd">Код регистрации :</label>
                {{ form.code(class="form-control") }}
              </div>
              {{ form.submit(class="btn btn-primary") }}
              <a href="{{ url_for("main.home")}}" class="btn btn-danger">На главную</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>